belanja1 = input("Masukkan daftar belanja 1: ")
belanja2 = input("Masukkan daftar belanja 2: ")
tambahan1 = input("Tambahkan data ke daftar belanja 1: ")
tambahan2 = input("Tambahkan data ke daftar belanja 2: ")
print("Daftar belanja 1 adalah",belanja1,",",tambahan1)
print("Daftar belanja 2 adalah",belanja2,",",tambahan2)